ini_open("speedshard_moneydungeon.ini")
global.dungeon_reset_modifier = ini_read_real("globals", "dungeon_reset_modifier", 6)
global.secret_room_chance = ini_read_real("globals", "secret_room_chance", 5)
global.contract_money_modifier = ini_read_real("globals", "contract_money_modifier", 1)
global.number_room_max = ini_read_real("globals", "number_room_max", 15)
global.number_room_min = ini_read_real("globals", "number_room_min", 5)
global.number_chest_max = ini_read_real("globals", "number_chest_max", 7)
global.number_chest_min = ini_read_real("globals", "number_chest_min", 5)
global.gold_multiplier = ini_read_real("globals", "gold_multiplier", 1)
ini_close()